# Generated by Django 4.2.5 on 2023-11-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_path', '0002_alter_path_created_alter_path_custom_field_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
